# makefile for pure_cpp_sum.cpp
# just run 'make'

CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++11

pure_cpp_sum: pure_cpp_sum.cpp
	$(CXX) $(CXXFLAGS) pure_cpp_sum.cpp -o pure_cpp_sum

clean:
	rm -f pure_cpp_sum